eth-light-client: add crate
dwallet-labs/dwallet-network pull request #36
Opened 2024-06-13 12:02 UTC by shaymalichi

2024-06-13 12:06 UTC, shaymalichi commented on crates/eth-light-client/Cargo.toml
> +#serde_json = "1.0.109"
```suggestion
```

2024-06-16 07:21 UTC, zeevmoney requested changes
This PR is not ready, base it on the correct branch.

2024-06-16 12:32 UTC, zeevmoney requested changes
This should be separated to multiple PRs, see comments, closing.

2024-06-16 12:32 UTC, zeevmoney commented on crates/eth-light-client/src/config.rs
> +use helios::prelude::networks::Network;
Separate this to it's own PR

2024-06-16 12:32 UTC, zeevmoney commented on crates/eth-light-client/src/eth_state.rs
> +
Separate this to it's own PR

2024-06-16 12:32 UTC, zeevmoney commented on Cargo.lock
Why did you delete this file?

2024-06-16 12:32 UTC, zeevmoney commented on crates/eth-light-client/src/light_client.rs
> +impl EthLightClient {
Separate this to it's own PR + tests

2024-06-16 12:32 UTC, zeevmoney commented on crates/eth-light-client/src/proof.rs
> +pub fn verify_proof(proof: &[Bytes], root: &[u8], path: &[u8], value: &Vec<u8>) -> bool {
Separate to it's own PR +tests

2024-06-16 12:32 UTC, zeevmoney commented on crates/eth-light-client/src/update.rs
> +#[derive(Debug, serde::Deserialize, serde::Serialize, Clone)]
Separate to it's own PR + tests

2024-06-16 12:32 UTC, closed without merging