450 secret share transfer
dwallet-labs/dwallet-network pull request #452
Opened 2024-12-31 12:56 UTC by ItayLevyOfficial

2025-01-01 13:07 UTC, yaelAbergel approved these changes

2025-01-01 13:07 UTC, yaelAbergel commented on sdk/dwallet-mpc-wasm/src/lib.rs
> +}
```suggestion
#[wasm_bindgen]
pub fn generate_secp_cg_keypair_from_seed(seed: &[u8]) -> Result<JsValue, JsError> {
    let (public_key, private_key) =
        generate_secp_cg_keypair_from_seed_internal(
            seed.try_into().expect("seed must be 32 bytes long"),
        )
            .map_err(to_js_err)?;
    Ok(serde_wasm_bindgen::to_value(&(public_key, private_key))?)
}
```
If it doesn't work, then just remove the magic number.

2025-01-01 13:07 UTC, yaelAbergel commented on sdk/typescript/src/dwallet-mpc/encrypt-user-share.ts
> +type EncryptionKeyPair = {
use interface

2025-01-01 13:07 UTC, yaelAbergel commented on sdk/typescript/test/e2e/encrypt-user-share.test.ts
> +describe('encrypt user share', () => {
Use `Config` like at the dwallet_mpc tests

2025-01-01 13:33 UTC, ItayLevyOfficial commented on crates/pera-framework/packages/pera-system/sources/dwallet.move
> +        // TODO (#453): Verify the ed2551 public key matches the sender's address
verifies that the signature is valid. the commented out verification verifies that the public key is matching the address

2025-01-06 16:07 UTC, zeevmoney commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +pub fn generate_secp_cg_keypair_from_seed_internal(
i think there such a function in @yaelAbergel ,check with her.

2025-01-06 16:53 UTC, zeevmoney commented on sdk/dwallet-mpc-wasm/src/lib.rs
> +            seed.try_into().expect("seed must be 32 bytes long"),
remove the expect(), it panics.

2025-01-06 16:55 UTC, zeevmoney requested changes
see comments with todo(itay) and other comments.

2025-01-06 17:00 UTC, ItayLevyOfficial commented on crates/dwallet-mpc-centralized-party/src/lib.rs
> +pub fn generate_secp_cg_keypair_from_seed_internal(
Yael's function is generating a keypair & proof, which takes a long time. My function only generates the keypair.

2025-01-07 16:52 UTC, zeevmoney approved these changes

2025-01-08 13:28 UTC, closed without merging