dwallet-network/eth-light-client: add cli command create_eth_dwallet
dwallet-labs/dwallet-network pull request #84
Opened 2024-07-03 14:14 UTC by yuvalelmo

2024-08-12 11:58 UTC, zeevmoney requested changes
see comments

2024-08-12 11:58 UTC, zeevmoney commented on crates/sui-types/src/eth_dwallet.rs
> +/// Rust version of the Move dwallet_system::ethereum_state::EthState type
```suggestion
/// Rust version of the Move [`dwallet_system::ethereum_state::EthState`] type.
```

2024-08-12 11:58 UTC, zeevmoney commented on crates/sui/src/client_commands.rs
> +use crate::ethereum_client_commands::{create_eth_dwallet, EthClientCommands};
Note that `EthClientCommands` was imported twice (see line 91).

2024-08-12 11:58 UTC, zeevmoney commented on crates/sui/src/ethereum_client_commands.rs
> +use serde::{Deserialize, Serialize};
```suggestion
```

2024-08-12 11:58 UTC, zeevmoney commented on crates/sui/src/ethereum_client_commands.rs
> +use sui_json_rpc_types::{SuiExecutionStatus, SuiTransactionBlockEffectsAPI};
```suggestion
use sui_json_rpc_types::SuiExecutionStatus;
```

2024-08-12 11:58 UTC, zeevmoney commented on crates/sui/src/ethereum_client_commands.rs
> +}
Fix all `unwrap()`.

2024-08-12 12:47 UTC, zeevmoney approved these changes

2024-08-12 14:19 UTC, ycscaly approved these changes

2024-08-12 14:19 UTC, ycscaly commented on crates/sui-types/src/eth_dwallet.rs
> +    pub eth_smart_contract_addr: String,
```suggestion
    pub eth_smart_contract_address: String,
```

Please use fully abbreviated names

2024-08-12 14:19 UTC, ycscaly commented on crates/sui-types/src/eth_dwallet.rs
> +pub struct EthDWalletCap {
```suggestion
pub struct EthereumDWalletCap {
```
Please use fully abbreviated names

2024-08-13 16:31 UTC, zeevmoney approved these changes

2024-08-13 16:31 UTC, merged