dwallet-network/eth-light-client: added cli command init_ethereum_state
dwallet-labs/dwallet-network pull request #85
Opened 2024-07-03 14:27 UTC by yuvalelmo

2024-07-03 14:34 UTC, yuvalelmo commented on crates/sui/src/ethereum_client_commands.rs
> +/// Updates the current Ethereum state and creates a LatestEthState object
```suggestion
/// Initializes a shared LatestEthereumState object in the dWallet network
/// with the given checkpoint.
/// This function should only be called once to initialize the Ethereum state.
/// After the state is initialized, the Ethereum state object ID is saved in the configuration,
/// and the state is updated whenever a new state is successfully verified.
// todo(yuval): in future, we should load also the sync committee from binary data file.```

2024-08-12 12:05 UTC, zeevmoney requested changes
see comments

2024-08-12 12:05 UTC, zeevmoney commented on crates/sui-sdk/src/sui_client_config.rs
> +        let active_env = self.active_env.clone(); // Clone active_env to avoid immutable borrow
```suggestion
        let active_env = self.active_env.clone();
```

2024-08-12 12:05 UTC, zeevmoney commented on crates/sui-sdk/src/sui_client_config.rs
> +    pub fn update_ethereum_state_object_id(&mut self, object_id: ObjectID) {
return result, don't use `except()`, return an error if needed.

2024-08-12 12:05 UTC, zeevmoney commented on crates/sui/src/ethereum_client_commands.rs
> +        /// The corresponding Ethereum network
```suggestion
        /// The corresponding Ethereum network.
```

2024-08-12 12:05 UTC, zeevmoney commented on crates/sui/src/ethereum_client_commands.rs
> +// todo(yuval): in future, we should load also the sync committee from binary data file.```
```suggestion
```
open an issue.

2024-08-12 12:05 UTC, zeevmoney commented on crates/sui/src/ethereum_client_commands.rs
> +        .unwrap()
remove all `unwrap()`s

2024-08-12 14:23 UTC, ycscaly approved these changes

2024-08-13 17:14 UTC, zeevmoney approved these changes
fix suggestions and merge.

2024-08-13 17:14 UTC, zeevmoney commented on crates/sui-sdk/src/sui_client_config.rs
> +    }
```suggestion
    fn get_active_env_mut(&mut self) -> Result<&mut SuiEnv, anyhow::Error> {
        self.get_env_mut(&self.active_env).ok_or_else(|| {
            anyhow!(
                "Environment configuration wasn't found for the environment: [{}]",
                self.active_env.as_deref().unwrap_or("None")
            )
        })
    }
```

2024-08-13 17:14 UTC, zeevmoney commented on crates/sui-sdk/src/sui_client_config.rs
> +    }
```suggestion
    fn get_env_mut(&mut self, alias: &Option<String>) -> Option<&mut SuiEnv> {
        alias
            .as_ref()
            .and_then(|alias| self.envs.iter_mut().find(|env| &env.alias == alias))
            .or_else(|| self.envs.first_mut())
    }
```

2024-08-13 17:14 UTC, zeevmoney commented on crates/sui-sdk/src/sui_client_config.rs
> +    }
```suggestion
    pub fn update_ethereum_state_object_id(
        &mut self,
        object_id: ObjectID,
    ) -> Result<(), anyhow::Error> {
        let env = self.get_active_env_mut()?;
        env.eth_client_settings
            .as_mut()
            .map(|config| config.state_object_id = Some(object_id))
            .ok_or_else(|| {
                anyhow!(
                    "no Ethereum State object ID found for active environment: [{}]",
                    env.alias
                )
            })
    }
```

2024-08-14 07:59 UTC, merged